apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  namespace: edu-focused-lamarr
  labels:
    app: django-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - name: django-app
        image: pavel2232/django-k8s:latets
        ports:
        - containerPort: 80
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: postgres
                key: url
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: secret-django-app
                key: secret-key
          - name: ALLOWED_HOSTS
            valueFrom:
              secretKeyRef:
                name: secret-django-app
                key: allowed-hosts
