apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-jobs
spec:
  template:
    spec:
      containers:
      - name: migrate-django
        image: django_app
        imagePullPolicy: Never
        command: ["python",  "manage.py", "makemigrations", "--noinput"]
      restartPolicy: Never
  backoffLimit: 4

