apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
data:
  SECRET_KEY: sadsdsadluboy8898
  DATABASE_URL: postgres://test_k8s:OwOtBep9Frut@localhost:5432/test_k8s
  ALLOWED_HOSTS: 127.0.0.1,localhost
  